description = "Lists the dependents of the package."

prompt = """
Run the `list_dependents` tool to find the dependents of the package.

The user may pass the name of the package as an argument to this command.

If the user does not specify the name of the package as an argument,
the current package can be determined by examining the code or looking at the
output from `git remote -v` (typically the package is indicated by the
`origin` entry).

If `list_dependents` returns a not found error, try to find the package name
through alternate means. For example, for Go, the package name can be found
in the `go.mod` file.

If your attempts fail, ask the user for the name of their package.
"""
