name: Release Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    env:
        GOOS: darwin
        GOARCH: arm64
        STAGING: staging-darwin-arm64
        RELEASE_ARCHIVE: darwin.arm64.deps-extension.zip
        MCP_BINARY_NAME: depsmcp


    # strategy:
    #   matrix:
    #     os:
    #     - go: linux
    #       gcli: linux
    #     - go: windows
    #       gcli: windows
    #     - go: darwin
    #       gcli: darwin
    #     arch: [x64, arm64]
    #     # exclude:
    #     #   - os: windows
    #     #     arch: arm64
    #     #   - os: darwin
    #     #     arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.1

      - name: Create release folder
        run: |
          mkdir -p ${{ env.STAGING }}/commands
          cp gemini-extension.json ${{ env.STAGING }}
          cp commands/*.toml ${{ env.STAGING }}/commands/

      - name: Build binary
        run: |
          cd mcp
          go build -o ../${{ env.STAGING }}/${{ env. MCP_BINARY_NAME }}

      - name: Create release archive
        run: |
          mkdir -p release
          zip release/${{ env.RELEASE_ARCHIVE }} ${{ env.STAGING }}/*

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/${{ env.RELEASE_ARCHIVE }}
